"""Assemble the auto-generated cs_user_extra_operations.cpp.

Each Extractor that needs C++ user-file injection exposes a
``cpp_helpers(recipe)`` method returning a list of :class:`CppHelper` items.
This module deduplicates helpers across recipes (by helper name) and produces
the final cs_user_extra_operations.cpp source: includes + every helper as a
static function + a single ``cs_user_extra_operations`` entry point that
dispatches to each helper in order.
"""

from __future__ import annotations

from collections.abc import Sequence
from dataclasses import dataclass

from .errors import QoIError
from .recipe import Recipe
from .registry import get_extractor

_MANAGED_HEADER = """/*============================================================================
 * cs_user_extra_operations.cpp — auto-generated by csauto
 *
 * DO NOT EDIT — regenerated by csauto on `prepare`.
 *
 * Targets code_saturne >= 9.0 user-file API. Built from {n_recipes} QoI
 * recipe(s). Each helper below is contributed by a recipe extractor and
 * dispatched from cs_user_extra_operations.
 *============================================================================*/

#include "cs_headers.h"

#include <cstdio>

"""

_INJECTED_SOURCE_HEADER = """/*============================================================================
 * cs_user_csauto_qoi.cpp — auto-generated by csauto (injected mode)
 *
 * DO NOT EDIT — regenerated by csauto on `prepare`.
 *
 * Targets code_saturne >= 9.0 user-file API. Built from {n_recipes} QoI
 * recipe(s). The user is expected to call csauto_qoi_dispatch(domain) from
 * their own user-extra-operations function — see docs/qoi.md.
 *============================================================================*/

#include "cs_user_csauto_qoi.h"

#include <cstdio>

"""

_INJECTED_HEADER_TEXT = """/*============================================================================
 * cs_user_csauto_qoi.h — auto-generated by csauto (injected mode)
 *
 * DO NOT EDIT — regenerated by csauto on `prepare`.
 *
 * Include this header in the user file that defines user-extra-operations
 * and call csauto_qoi_dispatch(domain) from there to enable QoI extraction.
 *============================================================================*/

#pragma once

#include "cs_headers.h"

void csauto_qoi_dispatch(cs_domain_t *domain);
"""


@dataclass(frozen=True)
class CppHelper:
    """A single static helper function contributed by an extractor.

    Attributes:
        name: C identifier — also the dedup key. Two helpers with the same
              name must produce the same code; conflicting definitions raise.
        code: Full source of the static function, ending with a newline.
    """

    name: str
    code: str


def collect_helpers(recipes: Sequence[Recipe]) -> dict[str, CppHelper]:
    """Walk the recipes and gather every unique C++ helper they need.

    Helpers are keyed by name. Two recipes contributing the same helper name
    with different bodies signal a programming error and raise QoIError.
    """
    helpers: dict[str, CppHelper] = {}
    for recipe in recipes:
        extractor_cls = get_extractor(recipe.type)
        extractor = extractor_cls()
        method = getattr(extractor, "cpp_helpers", None)
        if method is None:
            continue
        for helper in method(recipe):
            existing = helpers.get(helper.name)
            if existing is not None and existing.code != helper.code:
                raise QoIError(
                    f"Conflicting C++ helper {helper.name!r}: different recipes would emit incompatible bodies."
                )
            helpers[helper.name] = helper
    return helpers


def assemble_user_extra_operations(recipes: Sequence[Recipe]) -> str | None:
    """Render the full cs_user_extra_operations.cpp source (managed mode).

    Returns None if no recipe needs C++ injection — the caller is expected
    to skip writing any user file in that case.
    """
    helpers = collect_helpers(recipes)
    if not helpers:
        return None
    return _render_with_entry(
        helpers,
        header=_MANAGED_HEADER.format(n_recipes=len(recipes)),
        entry_signature="void\ncs_user_extra_operations(cs_domain_t *domain)",
    )


def assemble_dispatcher_files(recipes: Sequence[Recipe]) -> tuple[str, str] | None:
    """Render (header_text, source_text) for injected mode.

    The header declares ``csauto_qoi_dispatch(cs_domain_t *)``; the source
    contains every helper plus that function as the unified entry point.
    Returns None if no recipe needs C++ injection.
    """
    helpers = collect_helpers(recipes)
    if not helpers:
        return None
    source = _render_with_entry(
        helpers,
        header=_INJECTED_SOURCE_HEADER.format(n_recipes=len(recipes)),
        entry_signature="void\ncsauto_qoi_dispatch(cs_domain_t *domain)",
    )
    return _INJECTED_HEADER_TEXT, source


def _render_with_entry(helpers: dict[str, CppHelper], *, header: str, entry_signature: str) -> str:
    """Render a full source file: header + deterministic helpers + dispatcher."""
    ordered_names = sorted(helpers)
    parts: list[str] = [header]
    for name in ordered_names:
        parts.append(helpers[name].code)
        parts.append("\n")
    parts.append(entry_signature + "\n{\n")
    for name in ordered_names:
        parts.append(f"  {name}(domain);\n")
    parts.append("}\n")
    return "".join(parts)


__all__ = [
    "CppHelper",
    "assemble_dispatcher_files",
    "assemble_user_extra_operations",
    "collect_helpers",
]
