"""Inject the auto-generated cs_user_extra_operations.cpp into case directories.

Mode 'managed' only — refuses to overwrite an existing user file. A future
phase will add mode 'injected' (coexistence with a user-authored file).
"""

from __future__ import annotations

from collections.abc import Sequence
from pathlib import Path

from .cpp import assemble_user_extra_operations
from .errors import QoIError
from .recipe import Recipe

# Same basename, two possible extensions (code_saturne accepts either).
_USER_FILE_BASENAME = "cs_user_extra_operations"
_USER_FILE_EXTENSIONS = (".cpp", ".cxx", ".cc", ".c")
_TARGET_FILENAME = f"{_USER_FILE_BASENAME}.cpp"


def inject_user_files_into_case(case_dir: Path, recipes: Sequence[Recipe]) -> Path | None:
    """Write the auto-generated user file for one case.

    Returns the path written, or None if no recipe needed C++ injection.
    Raises QoIError if a user-authored cs_user_extra_operations.* is already
    present in caseXXXX/SRC/ — that's the 'managed' mode contract.
    """
    if not recipes:
        return None
    source = assemble_user_extra_operations(recipes)
    if source is None:
        return None

    src_dir = case_dir / "SRC"
    existing = _find_existing_user_file(src_dir)
    target = src_dir / _TARGET_FILENAME

    if existing is not None and not _is_csauto_managed(existing):
        raise QoIError(
            f"User file already present at {existing} (case {case_dir.name}). "
            f"csauto's 'managed' mode requires a clean SRC/. Remove the file or "
            f"wait for the 'injected' coexistence mode (later phase)."
        )

    src_dir.mkdir(exist_ok=True)
    target.write_text(source, encoding="utf-8")
    return target


def inject_user_files_into_runs(runs_dir: Path, recipes: Sequence[Recipe]) -> list[Path]:
    """Inject user files in every caseXXXX/ under runs_dir.

    Stops at the first error so the user sees a clear message instead of a
    half-injected campaign.
    """
    if not recipes:
        return []
    if not runs_dir.is_dir():
        raise QoIError(f"runs_dir not found: {runs_dir}")

    written: list[Path] = []
    for case_dir in sorted(p for p in runs_dir.iterdir() if p.is_dir() and p.name.startswith("case")):
        path = inject_user_files_into_case(case_dir, recipes)
        if path is not None:
            written.append(path)
    return written


def _find_existing_user_file(src_dir: Path) -> Path | None:
    """Return the first cs_user_extra_operations.* found, if any."""
    if not src_dir.is_dir():
        return None
    for ext in _USER_FILE_EXTENSIONS:
        candidate = src_dir / f"{_USER_FILE_BASENAME}{ext}"
        if candidate.is_file():
            return candidate
    return None


def _is_csauto_managed(path: Path) -> bool:
    """True if the file was previously written by csauto (safe to overwrite).

    We use a marker line in the generated file header rather than a side-channel
    metadata file: it survives repository operations and is impossible to spoof
    accidentally.
    """
    try:
        head = path.read_text(encoding="utf-8", errors="ignore")[:512]
    except OSError:
        return False
    return "auto-generated by csauto" in head


__all__ = [
    "inject_user_files_into_case",
    "inject_user_files_into_runs",
]
