from __future__ import annotations

from pathlib import Path

import pytest

from csauto.qoi import Recipe
from csauto.qoi.errors import QoIError
from csauto.qoi.injection import (
    InjectionReport,
    inject_user_files_into_case,
    inject_user_files_into_runs,
)


def _force_recipe(name: str = "Cd", boundary: str = "wing") -> Recipe:
    return Recipe(
        name=name,
        type="force_coefficient",
        params={
            "boundary": boundary,
            "direction": [1.0, 0.0, 0.0],
            "ref_area": 1.0,
            "ref_velocity": 1.0,
            "ref_density": 1.0,
        },
    )


def _make_case(tmp_path: Path, name: str = "case0001") -> Path:
    case_dir = tmp_path / name
    case_dir.mkdir(parents=True)
    return case_dir


_USER_DEFINITION = (
    '#include "cs_headers.h"\n'
    "\n"
    "void cs_user_extra_operations(cs_domain_t *domain)\n"
    "{\n"
    "  /* hand-written by an engineer */\n"
    "}\n"
)

_USER_DEFINITION_WITH_DISPATCH = (
    '#include "cs_headers.h"\n'
    '#include "cs_user_csauto_qoi.h"\n'
    "\n"
    "void cs_user_extra_operations(cs_domain_t *domain)\n"
    "{\n"
    "  /* hand-written */\n"
    "  csauto_qoi_dispatch(domain);\n"
    "}\n"
)


# --- managed mode -----------------------------------------------------------


def test_managed_writes_extra_operations_file(tmp_path: Path) -> None:
    case_dir = _make_case(tmp_path)
    report = inject_user_files_into_case(case_dir, [_force_recipe()])
    assert isinstance(report, InjectionReport)
    assert report.mode == "managed"
    assert len(report.files_written) == 1
    target = report.files_written[0]
    assert target == case_dir / "SRC" / "cs_user_extra_operations.cpp"
    content = target.read_text(encoding="utf-8")
    assert "auto-generated by csauto" in content
    assert "csauto_qoi_force_wing" in content


def test_managed_creates_SRC_directory(tmp_path: Path) -> None:
    case_dir = _make_case(tmp_path)
    assert not (case_dir / "SRC").exists()
    inject_user_files_into_case(case_dir, [_force_recipe()])
    assert (case_dir / "SRC").is_dir()


def test_managed_empty_recipes_is_noop(tmp_path: Path) -> None:
    case_dir = _make_case(tmp_path)
    report = inject_user_files_into_case(case_dir, [])
    assert report.files_written == []
    assert not (case_dir / "SRC" / "cs_user_extra_operations.cpp").exists()


def test_managed_refuses_existing_user_authored_file(tmp_path: Path) -> None:
    case_dir = _make_case(tmp_path)
    src = case_dir / "SRC"
    src.mkdir()
    pre_existing = src / "cs_user_extra_operations.cpp"
    pre_existing.write_text(_USER_DEFINITION, encoding="utf-8")

    with pytest.raises(QoIError, match=r"already defined in cs_user_extra_operations\.cpp"):
        inject_user_files_into_case(case_dir, [_force_recipe()])
    assert "hand-written by an engineer" in pre_existing.read_text(encoding="utf-8")


@pytest.mark.parametrize("extension", [".c", ".cc", ".cxx"])
def test_managed_refuses_user_file_with_alternate_extension(tmp_path: Path, extension: str) -> None:
    case_dir = _make_case(tmp_path)
    src = case_dir / "SRC"
    src.mkdir()
    (src / f"cs_user_extra_operations{extension}").write_text(_USER_DEFINITION, encoding="utf-8")
    with pytest.raises(QoIError, match="already defined in"):
        inject_user_files_into_case(case_dir, [_force_recipe()])


def test_managed_refuses_when_function_defined_in_another_file(tmp_path: Path) -> None:
    case_dir = _make_case(tmp_path)
    src = case_dir / "SRC"
    src.mkdir()
    (src / "cs_user_source_terms.cpp").write_text(
        '#include "cs_headers.h"\n\nvoid cs_user_extra_operations(cs_domain_t *domain) {}\n',
        encoding="utf-8",
    )
    with pytest.raises(QoIError, match=r"already defined in cs_user_source_terms\.cpp"):
        inject_user_files_into_case(case_dir, [_force_recipe()])
    assert not (src / "cs_user_extra_operations.cpp").exists()


def test_managed_ignores_function_call_in_other_file(tmp_path: Path) -> None:
    case_dir = _make_case(tmp_path)
    src = case_dir / "SRC"
    src.mkdir()
    (src / "cs_user_initialization.cpp").write_text(
        '#include "cs_headers.h"\nvoid cs_user_initialization(cs_domain_t *domain){\n  cs_user_extra_operations(domain);\n}\n',
        encoding="utf-8",
    )
    report = inject_user_files_into_case(case_dir, [_force_recipe()])
    assert report.files_written and report.files_written[0].is_file()


def test_managed_ignores_mentions_in_comments(tmp_path: Path) -> None:
    case_dir = _make_case(tmp_path)
    src = case_dir / "SRC"
    src.mkdir()
    (src / "cs_user_boundary_conditions.cpp").write_text(
        '#include "cs_headers.h"\n/* see cs_user_extra_operations(cs_domain_t *) { ... */\nvoid x(void){}\n',
        encoding="utf-8",
    )
    report = inject_user_files_into_case(case_dir, [_force_recipe()])
    assert report.files_written and report.files_written[0].is_file()


def test_managed_ignores_forward_declaration(tmp_path: Path) -> None:
    case_dir = _make_case(tmp_path)
    src = case_dir / "SRC"
    src.mkdir()
    (src / "cs_user_headers.cpp").write_text(
        '#include "cs_headers.h"\n\nvoid cs_user_extra_operations(cs_domain_t *domain);\n',
        encoding="utf-8",
    )
    report = inject_user_files_into_case(case_dir, [_force_recipe()])
    assert report.files_written and report.files_written[0].is_file()


def test_managed_overwrites_previously_csauto_managed_file(tmp_path: Path) -> None:
    case_dir = _make_case(tmp_path)
    inject_user_files_into_case(case_dir, [_force_recipe(boundary="wing")])
    inject_user_files_into_case(case_dir, [_force_recipe(boundary="fuselage")])
    content = (case_dir / "SRC" / "cs_user_extra_operations.cpp").read_text(encoding="utf-8")
    assert "csauto_qoi_force_fuselage" in content
    assert "csauto_qoi_force_wing" not in content


# --- injected mode ----------------------------------------------------------


def test_injected_writes_csauto_qoi_pair(tmp_path: Path) -> None:
    case_dir = _make_case(tmp_path)
    report = inject_user_files_into_case(case_dir, [_force_recipe()], mode="injected")
    names = sorted(p.name for p in report.files_written)
    assert names == ["cs_user_csauto_qoi.cpp", "cs_user_csauto_qoi.h"]
    src_dir = case_dir / "SRC"
    cpp = (src_dir / "cs_user_csauto_qoi.cpp").read_text(encoding="utf-8")
    h = (src_dir / "cs_user_csauto_qoi.h").read_text(encoding="utf-8")
    assert "csauto_qoi_dispatch(cs_domain_t *domain)" in cpp
    assert "void csauto_qoi_dispatch(cs_domain_t *domain);" in h
    assert "cs_user_extra_operations" not in cpp


def test_injected_does_not_touch_existing_user_file(tmp_path: Path) -> None:
    case_dir = _make_case(tmp_path)
    src = case_dir / "SRC"
    src.mkdir()
    user_file = src / "cs_user_source_terms.cpp"
    user_file.write_text(
        '#include "cs_headers.h"\n\nvoid cs_user_extra_operations(cs_domain_t *domain){}\n',
        encoding="utf-8",
    )
    original = user_file.read_text(encoding="utf-8")
    report = inject_user_files_into_case(case_dir, [_force_recipe()], mode="injected")
    assert report.user_file_with_extra_ops == user_file
    assert user_file.read_text(encoding="utf-8") == original  # untouched
    assert report.dispatch_call_present is False
    assert report.needs_user_action is True


def test_injected_detects_dispatch_already_wired(tmp_path: Path) -> None:
    case_dir = _make_case(tmp_path)
    src = case_dir / "SRC"
    src.mkdir()
    (src / "cs_user_extra_operations.cpp").write_text(_USER_DEFINITION_WITH_DISPATCH, encoding="utf-8")
    report = inject_user_files_into_case(case_dir, [_force_recipe()], mode="injected")
    assert report.dispatch_call_present is True
    assert report.needs_user_action is False


def test_injected_is_idempotent(tmp_path: Path) -> None:
    case_dir = _make_case(tmp_path)
    r1 = inject_user_files_into_case(case_dir, [_force_recipe()], mode="injected")
    snapshots = {p: p.read_text(encoding="utf-8") for p in r1.files_written}
    r2 = inject_user_files_into_case(case_dir, [_force_recipe()], mode="injected")
    assert {p.name for p in r2.files_written} == {p.name for p in r1.files_written}
    for p in r2.files_written:
        assert p.read_text(encoding="utf-8") == snapshots[p]


def test_injected_refuses_pre_existing_non_managed_qoi_file(tmp_path: Path) -> None:
    case_dir = _make_case(tmp_path)
    src = case_dir / "SRC"
    src.mkdir()
    (src / "cs_user_csauto_qoi.cpp").write_text(
        "/* hand-written, not by csauto */\nvoid csauto_qoi_dispatch(cs_domain_t *d){}\n",
        encoding="utf-8",
    )
    with pytest.raises(QoIError, match="already exists in"):
        inject_user_files_into_case(case_dir, [_force_recipe()], mode="injected")


def test_invalid_mode_raises(tmp_path: Path) -> None:
    case_dir = _make_case(tmp_path)
    with pytest.raises(QoIError, match="Unknown qoi_mode"):
        inject_user_files_into_case(case_dir, [_force_recipe()], mode="exotic")


# --- inject_user_files_into_runs --------------------------------------------


def test_inject_into_runs_managed_returns_one_report_per_case(tmp_path: Path) -> None:
    runs = tmp_path / "RUNS"
    runs.mkdir()
    for name in ("case0001", "case0002", "case0003"):
        (runs / name).mkdir()
    (runs / "MESH").mkdir()  # non-case dir, must be ignored

    reports = inject_user_files_into_runs(runs, [_force_recipe()])
    assert {r.case_dir.name for r in reports} == {"case0001", "case0002", "case0003"}
    assert all(r.mode == "managed" for r in reports)
    assert all(r.files_written for r in reports)


def test_inject_into_runs_injected_writes_pair_per_case(tmp_path: Path) -> None:
    runs = tmp_path / "RUNS"
    runs.mkdir()
    for name in ("case0001", "case0002"):
        (runs / name).mkdir()
    reports = inject_user_files_into_runs(runs, [_force_recipe()], mode="injected")
    assert all(len(r.files_written) == 2 for r in reports)
    assert all(r.mode == "injected" for r in reports)


def test_inject_into_runs_no_recipes_is_noop(tmp_path: Path) -> None:
    runs = tmp_path / "RUNS"
    runs.mkdir()
    (runs / "case0001").mkdir()
    assert inject_user_files_into_runs(runs, []) == []


def test_inject_into_runs_raises_when_runs_dir_missing(tmp_path: Path) -> None:
    with pytest.raises(QoIError, match="runs_dir not found"):
        inject_user_files_into_runs(tmp_path / "ghost", [_force_recipe()])


def test_inject_into_runs_managed_stops_on_first_conflict(tmp_path: Path) -> None:
    runs = tmp_path / "RUNS"
    runs.mkdir()
    (runs / "case0001").mkdir()
    case2 = runs / "case0002"
    case2.mkdir()
    (case2 / "SRC").mkdir()
    (case2 / "SRC" / "cs_user_extra_operations.cpp").write_text(_USER_DEFINITION, encoding="utf-8")
    (runs / "case0003").mkdir()

    with pytest.raises(QoIError, match="already defined in"):
        inject_user_files_into_runs(runs, [_force_recipe()])
    # case0001 was processed before the conflict; case0003 must not have been touched.
    assert (runs / "case0001" / "SRC" / "cs_user_extra_operations.cpp").is_file()
    assert not (runs / "case0003" / "SRC").exists()
