from __future__ import annotations

import pytest

from csauto.qoi import Recipe
from csauto.qoi.cpp import CppHelper, assemble_user_extra_operations, collect_helpers
from csauto.qoi.errors import QoIError
from csauto.qoi.registry import _REGISTRY

# --- Fixtures ---------------------------------------------------------------


def _force_recipe(name: str, boundary: str) -> Recipe:
    return Recipe(
        name=name,
        type="force_coefficient",
        params={
            "boundary": boundary,
            "direction": [1.0, 0.0, 0.0],
            "ref_area": 1.0,
            "ref_velocity": 1.0,
            "ref_density": 1.0,
        },
    )


# --- collect_helpers --------------------------------------------------------


def test_collect_helpers_empty_recipes() -> None:
    assert collect_helpers([]) == {}


def test_collect_helpers_single_recipe() -> None:
    helpers = collect_helpers([_force_recipe("Cd", "wing")])
    assert list(helpers) == ["csauto_qoi_force_wing"]


def test_collect_helpers_dedupes_same_boundary_across_recipes() -> None:
    # Cd and Cl both on "wing" -> a single helper
    helpers = collect_helpers([_force_recipe("Cd", "wing"), _force_recipe("Cl", "wing")])
    assert list(helpers) == ["csauto_qoi_force_wing"]


def test_collect_helpers_distinct_boundaries_yield_distinct_helpers() -> None:
    helpers = collect_helpers([_force_recipe("Cd_w", "wing"), _force_recipe("Cd_f", "fuselage")])
    assert set(helpers) == {"csauto_qoi_force_wing", "csauto_qoi_force_fuselage"}


def test_collect_helpers_skips_extractors_without_cpp_helpers(monkeypatch: pytest.MonkeyPatch) -> None:
    """An extractor that does not implement cpp_helpers is a no-op for injection."""

    class NoCppExtractor:
        def validate(self, recipe: Recipe) -> None:
            return None

        def extract(self, ctx: object, recipe: Recipe) -> dict[str, float]:
            return {recipe.name: 0.0}

    monkeypatch.setitem(_REGISTRY, "scalar_only", NoCppExtractor)
    recipe = Recipe(name="X", type="scalar_only")
    assert collect_helpers([recipe]) == {}


def test_collect_helpers_detects_conflicting_definitions(monkeypatch: pytest.MonkeyPatch) -> None:
    """Two recipes contributing the same helper name with different bodies must raise."""

    class ConflictA:
        def validate(self, recipe: Recipe) -> None: ...
        def extract(self, ctx: object, recipe: Recipe) -> dict[str, float]:
            return {}

        def cpp_helpers(self, recipe: Recipe) -> list[CppHelper]:
            return [CppHelper(name="shared", code="static void shared() { /* A */ }\n")]

    class ConflictB:
        def validate(self, recipe: Recipe) -> None: ...
        def extract(self, ctx: object, recipe: Recipe) -> dict[str, float]:
            return {}

        def cpp_helpers(self, recipe: Recipe) -> list[CppHelper]:
            return [CppHelper(name="shared", code="static void shared() { /* B */ }\n")]

    monkeypatch.setitem(_REGISTRY, "conflict_a", ConflictA)
    monkeypatch.setitem(_REGISTRY, "conflict_b", ConflictB)
    with pytest.raises(QoIError, match="Conflicting C\\+\\+ helper"):
        collect_helpers([Recipe(name="A", type="conflict_a"), Recipe(name="B", type="conflict_b")])


# --- assemble_user_extra_operations ----------------------------------------


def test_assemble_returns_none_when_no_recipes_need_cpp() -> None:
    assert assemble_user_extra_operations([]) is None


def test_assemble_builds_full_source_with_main_dispatcher() -> None:
    src = assemble_user_extra_operations([_force_recipe("Cd_w", "wing"), _force_recipe("Cd_f", "fuselage")])
    assert src is not None
    assert "auto-generated by csauto" in src
    assert '#include "cs_headers.h"' in src
    # Both helpers as static functions
    assert "static void\ncsauto_qoi_force_wing(" in src
    assert "static void\ncsauto_qoi_force_fuselage(" in src
    # Single entry point that calls each
    assert "cs_user_extra_operations(cs_domain_t *domain)" in src
    assert "csauto_qoi_force_wing(domain);" in src
    assert "csauto_qoi_force_fuselage(domain);" in src


def test_assemble_helpers_are_emitted_in_deterministic_order() -> None:
    """Reordering the recipes must not change the output (alphabetical helper order)."""
    a = assemble_user_extra_operations([_force_recipe("Cd_w", "wing"), _force_recipe("Cd_f", "fuselage")])
    b = assemble_user_extra_operations([_force_recipe("Cd_f", "fuselage"), _force_recipe("Cd_w", "wing")])
    assert a == b


def test_assemble_includes_recipe_count_in_header() -> None:
    src = assemble_user_extra_operations([_force_recipe("Cd", "wing"), _force_recipe("Cl", "wing")])
    assert src is not None
    assert "Built from 2 QoI" in src
