from __future__ import annotations

from pathlib import Path

import pytest

from csauto.qoi import Recipe
from csauto.qoi.errors import QoIError
from csauto.qoi.injection import (
    inject_user_files_into_case,
    inject_user_files_into_runs,
)


def _force_recipe(name: str = "Cd", boundary: str = "wing") -> Recipe:
    return Recipe(
        name=name,
        type="force_coefficient",
        params={
            "boundary": boundary,
            "direction": [1.0, 0.0, 0.0],
            "ref_area": 1.0,
            "ref_velocity": 1.0,
            "ref_density": 1.0,
        },
    )


def _make_case(tmp_path: Path, name: str = "case0001") -> Path:
    case_dir = tmp_path / name
    case_dir.mkdir(parents=True)
    return case_dir


# --- inject_user_files_into_case --------------------------------------------


def test_inject_into_case_writes_file_in_SRC(tmp_path: Path) -> None:
    case_dir = _make_case(tmp_path)
    target = inject_user_files_into_case(case_dir, [_force_recipe()])
    assert target == case_dir / "SRC" / "cs_user_extra_operations.cpp"
    assert target.is_file()
    content = target.read_text(encoding="utf-8")
    assert "auto-generated by csauto" in content
    assert "csauto_qoi_force_wing" in content


def test_inject_into_case_creates_SRC_directory(tmp_path: Path) -> None:
    case_dir = _make_case(tmp_path)
    assert not (case_dir / "SRC").exists()
    inject_user_files_into_case(case_dir, [_force_recipe()])
    assert (case_dir / "SRC").is_dir()


def test_inject_into_case_returns_none_with_empty_recipes(tmp_path: Path) -> None:
    case_dir = _make_case(tmp_path)
    assert inject_user_files_into_case(case_dir, []) is None
    assert not (case_dir / "SRC" / "cs_user_extra_operations.cpp").exists()


_USER_DEFINITION = (
    '#include "cs_headers.h"\n'
    "\n"
    "void cs_user_extra_operations(cs_domain_t *domain)\n"
    "{\n"
    "  /* hand-written by an engineer */\n"
    "}\n"
)


def test_inject_into_case_refuses_existing_user_authored_file(tmp_path: Path) -> None:
    case_dir = _make_case(tmp_path)
    src = case_dir / "SRC"
    src.mkdir()
    pre_existing = src / "cs_user_extra_operations.cpp"
    pre_existing.write_text(_USER_DEFINITION, encoding="utf-8")

    with pytest.raises(QoIError, match=r"already defined in cs_user_extra_operations\.cpp"):
        inject_user_files_into_case(case_dir, [_force_recipe()])
    # And the file must be untouched.
    assert "hand-written by an engineer" in pre_existing.read_text(encoding="utf-8")


@pytest.mark.parametrize("extension", [".c", ".cc", ".cxx"])
def test_inject_into_case_refuses_user_file_with_alternate_extension(tmp_path: Path, extension: str) -> None:
    case_dir = _make_case(tmp_path)
    src = case_dir / "SRC"
    src.mkdir()
    pre_existing = src / f"cs_user_extra_operations{extension}"
    pre_existing.write_text(_USER_DEFINITION, encoding="utf-8")
    with pytest.raises(QoIError, match="already defined in"):
        inject_user_files_into_case(case_dir, [_force_recipe()])


def test_inject_into_case_refuses_when_function_defined_in_another_file(tmp_path: Path) -> None:
    """The function is allowed in any *.cpp under SRC/; csauto must still detect it.

    Reproduces the real-world bug where a template's cs_user_source_terms.cpp
    also defined cs_user_extra_operations, causing a link-time duplicate symbol.
    """
    case_dir = _make_case(tmp_path)
    src = case_dir / "SRC"
    src.mkdir()
    source_terms = src / "cs_user_source_terms.cpp"
    source_terms.write_text(
        '#include "cs_headers.h"\n'
        "\n"
        "void cs_user_extra_operations(cs_domain_t *domain)\n"
        "{\n"
        "  /* historical: lives here for legacy reasons */\n"
        "}\n"
        "\n"
        "void cs_user_source_terms(cs_domain_t *domain, int field_id, cs_real_t *st_exp, cs_real_t *st_imp)\n"
        "{\n"
        "}\n",
        encoding="utf-8",
    )
    with pytest.raises(QoIError, match=r"already defined in cs_user_source_terms\.cpp"):
        inject_user_files_into_case(case_dir, [_force_recipe()])
    # No csauto file must have been written.
    assert not (src / "cs_user_extra_operations.cpp").exists()


def test_inject_ignores_function_call_in_other_file(tmp_path: Path) -> None:
    """A call site (not a definition) must NOT trigger the conflict guard."""
    case_dir = _make_case(tmp_path)
    src = case_dir / "SRC"
    src.mkdir()
    (src / "cs_user_initialization.cpp").write_text(
        '#include "cs_headers.h"\n'
        "\n"
        "void cs_user_initialization(cs_domain_t *domain)\n"
        "{\n"
        "  cs_user_extra_operations(domain);  /* legit call site */\n"
        "}\n",
        encoding="utf-8",
    )
    target = inject_user_files_into_case(case_dir, [_force_recipe()])
    assert target is not None
    assert target.is_file()


def test_inject_ignores_mentions_in_comments(tmp_path: Path) -> None:
    """A comment mentioning cs_user_extra_operations must NOT block injection."""
    case_dir = _make_case(tmp_path)
    src = case_dir / "SRC"
    src.mkdir()
    (src / "cs_user_boundary_conditions.cpp").write_text(
        '#include "cs_headers.h"\n'
        "\n"
        "/* This file works together with cs_user_extra_operations(cs_domain_t *) {\n"
        "   ...which lives in another file. */\n"
        "\n"
        "void cs_user_boundary_conditions_setup(void) {}\n",
        encoding="utf-8",
    )
    target = inject_user_files_into_case(case_dir, [_force_recipe()])
    assert target is not None
    assert target.is_file()


def test_inject_ignores_forward_declaration(tmp_path: Path) -> None:
    """A forward declaration (no body) must NOT count as a definition."""
    case_dir = _make_case(tmp_path)
    src = case_dir / "SRC"
    src.mkdir()
    (src / "cs_user_headers.cpp").write_text(
        '#include "cs_headers.h"\n\nvoid cs_user_extra_operations(cs_domain_t *domain);   /* fwd decl */\n',
        encoding="utf-8",
    )
    target = inject_user_files_into_case(case_dir, [_force_recipe()])
    assert target is not None
    assert target.is_file()


def test_inject_into_case_overwrites_previously_csauto_managed_file(tmp_path: Path) -> None:
    """Re-running prepare should refresh the generated file in place."""
    case_dir = _make_case(tmp_path)
    # First injection establishes the marker
    inject_user_files_into_case(case_dir, [_force_recipe(boundary="wing")])
    # A second prepare with a different boundary should succeed and rewrite
    inject_user_files_into_case(case_dir, [_force_recipe(boundary="fuselage")])
    content = (case_dir / "SRC" / "cs_user_extra_operations.cpp").read_text(encoding="utf-8")
    assert "csauto_qoi_force_fuselage" in content
    assert "csauto_qoi_force_wing" not in content


# --- inject_user_files_into_runs --------------------------------------------


def test_inject_into_runs_walks_every_case(tmp_path: Path) -> None:
    runs = tmp_path / "RUNS"
    runs.mkdir()
    for name in ("case0001", "case0002", "case0003"):
        (runs / name).mkdir()
    # Non-case directory must be ignored
    (runs / "MESH").mkdir()

    written = inject_user_files_into_runs(runs, [_force_recipe()])
    assert {p.parent.parent.name for p in written} == {"case0001", "case0002", "case0003"}
    assert all(p.name == "cs_user_extra_operations.cpp" for p in written)


def test_inject_into_runs_no_recipes_is_noop(tmp_path: Path) -> None:
    runs = tmp_path / "RUNS"
    runs.mkdir()
    (runs / "case0001").mkdir()
    assert inject_user_files_into_runs(runs, []) == []
    assert not (runs / "case0001" / "SRC").exists()


def test_inject_into_runs_raises_when_runs_dir_missing(tmp_path: Path) -> None:
    missing = tmp_path / "ghost"
    with pytest.raises(QoIError, match="runs_dir not found"):
        inject_user_files_into_runs(missing, [_force_recipe()])


def test_inject_into_runs_stops_on_first_conflict(tmp_path: Path) -> None:
    runs = tmp_path / "RUNS"
    runs.mkdir()
    (runs / "case0001").mkdir()
    case2 = runs / "case0002"
    case2.mkdir()
    (case2 / "SRC").mkdir()
    (case2 / "SRC" / "cs_user_extra_operations.cpp").write_text(_USER_DEFINITION, encoding="utf-8")
    (runs / "case0003").mkdir()

    with pytest.raises(QoIError, match="already defined in"):
        inject_user_files_into_runs(runs, [_force_recipe()])
    # case0001 was processed before the conflict; case0003 must not have been touched.
    assert (runs / "case0001" / "SRC" / "cs_user_extra_operations.cpp").is_file()
    assert not (runs / "case0003" / "SRC").exists()
