from __future__ import annotations

from pathlib import Path

import pytest

from csauto.qoi import Recipe
from csauto.qoi.errors import QoIError
from csauto.qoi.injection import (
    inject_user_files_into_case,
    inject_user_files_into_runs,
)


def _force_recipe(name: str = "Cd", boundary: str = "wing") -> Recipe:
    return Recipe(
        name=name,
        type="force_coefficient",
        params={
            "boundary": boundary,
            "direction": [1.0, 0.0, 0.0],
            "ref_area": 1.0,
            "ref_velocity": 1.0,
            "ref_density": 1.0,
        },
    )


def _make_case(tmp_path: Path, name: str = "case0001") -> Path:
    case_dir = tmp_path / name
    case_dir.mkdir(parents=True)
    return case_dir


# --- inject_user_files_into_case --------------------------------------------


def test_inject_into_case_writes_file_in_SRC(tmp_path: Path) -> None:
    case_dir = _make_case(tmp_path)
    target = inject_user_files_into_case(case_dir, [_force_recipe()])
    assert target == case_dir / "SRC" / "cs_user_extra_operations.cpp"
    assert target.is_file()
    content = target.read_text(encoding="utf-8")
    assert "auto-generated by csauto" in content
    assert "csauto_qoi_force_wing" in content


def test_inject_into_case_creates_SRC_directory(tmp_path: Path) -> None:
    case_dir = _make_case(tmp_path)
    assert not (case_dir / "SRC").exists()
    inject_user_files_into_case(case_dir, [_force_recipe()])
    assert (case_dir / "SRC").is_dir()


def test_inject_into_case_returns_none_with_empty_recipes(tmp_path: Path) -> None:
    case_dir = _make_case(tmp_path)
    assert inject_user_files_into_case(case_dir, []) is None
    assert not (case_dir / "SRC" / "cs_user_extra_operations.cpp").exists()


def test_inject_into_case_refuses_existing_user_authored_file(tmp_path: Path) -> None:
    case_dir = _make_case(tmp_path)
    src = case_dir / "SRC"
    src.mkdir()
    pre_existing = src / "cs_user_extra_operations.cpp"
    pre_existing.write_text("// hand-written by an engineer\nvoid cs_user_extra_operations() {}\n", encoding="utf-8")

    with pytest.raises(QoIError, match="User file already present"):
        inject_user_files_into_case(case_dir, [_force_recipe()])
    # And the file must be untouched.
    assert pre_existing.read_text(encoding="utf-8").startswith("// hand-written")


@pytest.mark.parametrize("extension", [".c", ".cc", ".cxx"])
def test_inject_into_case_refuses_user_file_with_alternate_extension(tmp_path: Path, extension: str) -> None:
    case_dir = _make_case(tmp_path)
    src = case_dir / "SRC"
    src.mkdir()
    pre_existing = src / f"cs_user_extra_operations{extension}"
    pre_existing.write_text("// hand-written\n", encoding="utf-8")
    with pytest.raises(QoIError, match="User file already present"):
        inject_user_files_into_case(case_dir, [_force_recipe()])


def test_inject_into_case_overwrites_previously_csauto_managed_file(tmp_path: Path) -> None:
    """Re-running prepare should refresh the generated file in place."""
    case_dir = _make_case(tmp_path)
    # First injection establishes the marker
    inject_user_files_into_case(case_dir, [_force_recipe(boundary="wing")])
    # A second prepare with a different boundary should succeed and rewrite
    inject_user_files_into_case(case_dir, [_force_recipe(boundary="fuselage")])
    content = (case_dir / "SRC" / "cs_user_extra_operations.cpp").read_text(encoding="utf-8")
    assert "csauto_qoi_force_fuselage" in content
    assert "csauto_qoi_force_wing" not in content


# --- inject_user_files_into_runs --------------------------------------------


def test_inject_into_runs_walks_every_case(tmp_path: Path) -> None:
    runs = tmp_path / "RUNS"
    runs.mkdir()
    for name in ("case0001", "case0002", "case0003"):
        (runs / name).mkdir()
    # Non-case directory must be ignored
    (runs / "MESH").mkdir()

    written = inject_user_files_into_runs(runs, [_force_recipe()])
    assert {p.parent.parent.name for p in written} == {"case0001", "case0002", "case0003"}
    assert all(p.name == "cs_user_extra_operations.cpp" for p in written)


def test_inject_into_runs_no_recipes_is_noop(tmp_path: Path) -> None:
    runs = tmp_path / "RUNS"
    runs.mkdir()
    (runs / "case0001").mkdir()
    assert inject_user_files_into_runs(runs, []) == []
    assert not (runs / "case0001" / "SRC").exists()


def test_inject_into_runs_raises_when_runs_dir_missing(tmp_path: Path) -> None:
    missing = tmp_path / "ghost"
    with pytest.raises(QoIError, match="runs_dir not found"):
        inject_user_files_into_runs(missing, [_force_recipe()])


def test_inject_into_runs_stops_on_first_conflict(tmp_path: Path) -> None:
    runs = tmp_path / "RUNS"
    runs.mkdir()
    (runs / "case0001").mkdir()
    case2 = runs / "case0002"
    case2.mkdir()
    (case2 / "SRC").mkdir()
    (case2 / "SRC" / "cs_user_extra_operations.cpp").write_text("// hand-written\n", encoding="utf-8")
    (runs / "case0003").mkdir()

    with pytest.raises(QoIError, match="User file already present"):
        inject_user_files_into_runs(runs, [_force_recipe()])
    # case0001 was processed before the conflict; case0003 must not have been touched.
    assert (runs / "case0001" / "SRC" / "cs_user_extra_operations.cpp").is_file()
    assert not (runs / "case0003" / "SRC").exists()
